//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficVilationsDesktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailedViolationsInfo
    {
        public int Violation_ID { get; set; }
        public System.DateTime Date_time { get; set; }
        public string Place { get; set; }
        public decimal Fine_Amount { get; set; }
        public string Payment_Status { get; set; }
        public string DriverFullName { get; set; }
        public string License { get; set; }
        public string VehicleInfo { get; set; }
        public string ViolationTypeName { get; set; }
        public string ViolationTypeDescription { get; set; }
    }
}
