//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrafficVilationsDesktop.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Violation
    {
        public int Violation_ID { get; set; }
        public int Driver_ID { get; set; }
        public int Vehicle_ID { get; set; }
        public int Violation_Type_ID { get; set; }
        public System.DateTime Date_Time { get; set; }
        public string Place { get; set; }
        public decimal Fine_Amount { get; set; }
        public int Payment_Status_ID { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Driver Driver1 { get; set; }
        public virtual Payment_Status Payment_Status { get; set; }
        public virtual Vehicle Vehicle { get; set; }
        public virtual Violation_Types Violation_Types { get; set; }
    }
}
